start:
	ansible-playbook ../playbooks/pb_tags1.yaml -i ../inventory-file/hex.ini

add_users:
	ansible-playbook ../playbooks/pb_tags1.yaml -i ../inventory-file/hex.ini --tags users

nodejs:
	ansible-playbook ../playbooks/pb_tags1.yaml -i ../inventory-file/hex.ini --tags nodejs

nodejs_instl:
	ansible-playbook ../playbooks/pb_tags1.yaml -i ../inventory-file/hex.ini --tags nodejs_instl

nodejs_ver:
	ansible-playbook ../playbooks/pb_tags1.yaml -i ../inventory-file/hex.ini --tags nodejs_ver

make_instl:
	ansible-playbook ../playbooks/pb_tags1.yaml -i ../inventory-file/hex.ini --tags make

git_instl:
	ansible-playbook ../playbooks/pb_tags1.yaml -i ../inventory-file/hex.ini --tags git
